### ISSUE TITLE
21.05 release branch

### ISSUE THREAD

**Issue by markuskowa** [markuskowa/NixOS-QChem#60]
We should create a branch, which is compatible with `nixos-21.05`, soon.

Items to wait for before we branch:
* [x] `openblas-0.3.15` gets backported to 21.05, and the AVX512 fix has been remove again.
* [x] Merge https://github.com/markuskowa/NixOS-QChem/pull/59
* [x] Maybe merge [`pysisyphus`](https://github.com/markuskowa/NixOS-QChem/pull/31)? : (cc @sheepforce, we can also backport it)

After the branch-off we can start removing packages that have been [ported to upstream nixpkgs](https://github.com/markuskowa/NixOS-QChem/issues/56)

**Comment by sheepforce** [comment]
Regarding Pysisyphus we should know more somewhere next week. We will see if we can sort out all the issues we are facing there. The branch is unfortunately a bit messy but contains otherwise important fixes (like PySCF bug fix, NWchem assertion fix and XTB pkg-config support). In case we cannot solve this in a reasonable time frame, we can just cherry pick those changes, that are independent of Pysis and merge them separately before branching.

**Comment by markuskowa** [comment]
I have opened the 21.05 branch now, since we already start to diverge from nixpkgs master (see e.g.: https://github.com/markuskowa/NixOS-QChem/pull/68). We can always back port patches later if needed.

We are still waiting for the AVX512 fix though.

**Comment by markuskowa** [comment]
OK, the AVX512 fix in openblas has now reached the nixos-21.05 channel. I have removed the fix in our 21.05 branch 029550200abd6310d367809a33bb675b14eeadd7.
`NixOS-QChem-21.05` is officially ready now.
